### PR TITLE
Full support for server-side password and passwordless login

### PR DESCRIPTION
**Pull request by chriscarrollsmith**
I think I've managed to add support for server-side password and magic link login, including signup and password recovery. Probably still need to add some use of loading dots, and maybe some safeguards to keep people from hitting the buttons too many times. Also a toggle to show/hide password fields. But the basic functionality is all here.

I also implemented the other changes I suggested throughout my code review.

Thank you for your heroic work to bring this template up-to-date; you are going to save me a lot of time!

### CODE REVIEW

**Comment by rayne1066** [comment]
Hi there,

First of all, I want to express my appreciation for the improvements you've made to the repo. The changes you've implemented have enhanced the codebase.

However, I've encountered an issue with the 'Stripe billing_portal.session.created' functionality after incorporating your changes into my own repository. Specifically, it seems to be generating a return URL with an extra slash, resulting in URLs like 'xxxx.vercel.app//account', which triggers an error.

Upon closer inspection, I noticed some inconsistencies in how `{url}`, the usage of slashes '/', and routing for additional paths are handled across different parts of the codebase. For example, in '/api/create-checkout-session/route.ts', there are instances of '/signup' and '/account', but in '/signin/route.ts', 'auth' appears without a trailing slash. My understanding, based on the `{url}` definition in 'helpers.ts', was that all URLs should have a trailing slash appended. 

My concern is whether this inconsistency in URL formatting could potentially lead to URLs like 'signup' and 'account' resulting in '//' (double slashes), which might explain the series of 500 errors I'm encountering during the login process. It's worth noting that while these errors occur, the events are successfully registered with Supabase, as indicated in the logs. Additionally, a page refresh after the error redirects to the customer portal.

I'm relatively new to TypeScript and have primarily worked with Python frameworks, so I apologize if my question seems straightforward or if I've misunderstood something. Any clarification or guidance on how to address this issue would be greatly appreciated.

I have also had some similar Errors with the original Commit that dalkommatt above did as well,  albeit less. The one thing I cant get to work across all platforms is the magic link for the email.  It sends the emails and logs them in supabase, when one goes to click on it, it generates a 500 auth error.  

I have gone through several times and triple checked my API keys and env and feel very confident it is not a secret or OAuth issue in Github.

Thank you for your assistance!

Best regards,
Rayne

**Comment by chriscarrollsmith** [comment]
Thanks for the heads up. Magic link was working last time I tried it, but possibly it's a platform-specific link-handling issue. I will take a look at this first thing tomorrow to iron out the inconsistencies in handling of urls.

**Comment by rayne1066** [comment]
I reverted to Dalkommatt's last commit, and deleted an / that was present in auth/, account, etc.
It appears to gone some ways towards fixing the problem.  Looking through the commits since the large PR that he did, there was a sudden change to adding / in some places, I would suggest that you search getURL and you will see what I mean.
An example for route.ts from checkout.

---
import { cookies } from 'next/headers';
import { createClient } from '@/utils/supabase/server';
import { stripe } from '@/utils/stripe';
import { createOrRetrieveCustomer } from '@/utils/supabase/admin';
import { getURL } from '@/utils/helpers';

export async function POST(req: Request) {
  if (req.method === 'POST') {
    // 1. Destructure the price and quantity from the POST body
    const { price, quantity = 1, metadata = {} } = await req.json();

    try {
      // 2. Get the user from Supabase auth
      const cookieStore = cookies();
      const supabase = createClient(cookieStore);

      const {
        data: { user }
      } = await supabase.auth.getUser();

      // 3. Retrieve or create the customer in Stripe
      const customer = await createOrRetrieveCustomer({
        uuid: user?.id || '',
        email: user?.email || ''
      });

      // 4. Create a checkout session in Stripe
      let session;
      if (price.type === 'recurring') {
        session = await stripe.checkout.sessions.create({
          billing_address_collection: 'required',
          customer,
          customer_update: {
            address: 'auto'
          },
          line_items: [
            {
              price: price.id,
              quantity
            }
          ],
          mode: 'subscription',
          allow_promotion_codes: true,
          subscription_data: {
            metadata
          },
          success_url: `${getURL()}account`
        });
      } else if (price.type === 'one_time') {
        session = await stripe.checkout.sessions.create({
          billing_address_collection: 'required',
          customer,
          customer_update: {
            address: 'auto'
          },
          line_items: [
            {
              price: price.id,
              quantity
            }
          ],
          mode: 'payment',
          allow_promotion_codes: true,
          success_url: `${getURL()}account`,
          cancel_url: `${getURL()}`
          //------------>rayne1066 changes
        });
      }

      if (session) {
        return new Response(JSON.stringify({ sessionId: session.id }), {
          status: 200
        });
      } else {
        return new Response(
          JSON.stringify({
            error: { statusCode: 500, message: 'Session is not defined' }
          }),
          { status: 500 }
        );
      }
    } catch (err: any) {
      console.log(err);
      return new Response(JSON.stringify(err), { status: 500 });
    }
  } else {
    return new Response('Method Not Allowed', {
      headers: { Allow: 'POST' },
      status: 405
    });
  }
}
----------
The other major breaking one I think was  line 33 in app/signin 

  const redirectURL = `${getURL()}auth/callback`; //--> rayne1066 removed slash before auth, seems to reworking now after deleting cookies and starting over. Can only get to work in Edge, chrome is up to date and cookies cleared. Ran on production.

**Comment by rayne1066** [comment]
Many thanks for your assistance,  I am a complete neophyte to TS so I apologize is what I did was a stab in the dark!

**Comment by chriscarrollsmith** [comment]
I changed the behavior of getURL so it now takes a `path` argument and automatically takes care of joining origin to path with a single front slash. Try it out and let me know if it solves your issues.

**Comment by chriscarrollsmith** [comment]
Looks like there's still a Stripe checkout issue on Chrome. Will do some more debugging.

**Comment by chriscarrollsmith** [comment]
There were a couple bugs, one caused by incorrect error handling in the createOrRetrieveCustomer function, and the other caused by a change to how trial periods were handled. I have resolved both issues, and it should be working now. Let me know if you run into further trouble.

**Comment by chriscarrollsmith** [comment]
Fixed some more bugs related to magic links and added full support for error handling when opening Stripe checkout or customer portal.

**Comment by dalkommatt** [comment]
@dijonmusters do you want to stick with just OAuth, do [OAuth + OTP](https://github.com/vercel/nextjs-subscription-payments/pull/278#issuecomment-1835813701), or do the full monty like in Chris's PR here?

**Comment by leerob** [comment]
Thank you for this!

**Pull request merged**
